blank_issues_enabled: true
version: 2.1
contact_links:
  - name: ðŸ“– Nixpacks documentation
    url: https://nixpacks.com/
    about: Documentation about Nixpacks
  - name: ðŸš… Railway
    url: https://railway.app/
    about: Railway homepage
  - name: Railway Discord
    url: discord.gg/railway
    about: Contact the Railway team for support via Discord

