[alias]
generate_plan_tests = "test --package nixpacks --lib --test generate_plan_tests"
snapshot = "insta test --review -- --test generate_plan_tests"
lint-fix = "clippy --fix --allow-dirty --allow-staged --all-targets --all-features -- -D warnings"
